name: Build and Distribute

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Decode Google Service Json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo "$KEYSTORE_BASE64" | base64 --decode > app/keystore.jks
             echo "KEYSTORE_FILE=${{ github.workspace }}/app/keystore.jks" >> $GITHUB_ENV

      - name: Build Prod Release APK

        env:
          KEYSTORE_FILE: app/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.PROD_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.PROD_KEY_PASSWORD }}
        run: ./gradlew assembleProdRelease

      - name: List APK outputs (debug step)
        run: ls -R app/build/outputs/apk/

      - name: Upload to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npx firebase-tools appdistribution:distribute \
            app/build/outputs/apk/prod/release/app-prod-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups "testers" \
            --release-notes "New release build from GitHub Actions - Commit: ${{ github.sha }}"

      - name: Grant Execute Permission For Gradle
        run: chmod +x gradlew

      - name: Build Debug APK
        env:
          PROD_BASE_URL: ${{ secrets.PROD_BASE_URL }}
          PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
        run: ./gradlew assembleProdDebug

      - name: Notify Slack
        if: success()
        uses: slackApi/slack-github-action@v2
        with:
          webhook-type: incoming-webhook
          payload: |
            {
              "text": ":tada: *Build Succeeded!* :white_check_mark:\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}\n*Triggered by:* ${{ github.actor }}"
            }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK }}
